---
# defaults file for rabbitmq-cluster

# Info about cluster nodes, need to edit changes here if inventory file changes
master:
  ip: '192.168.33.10'
  name: 'master'

slave01:
  ip: '192.168.33.11'
  name: 'slave01'

slave02:
  ip: '192.168.33.12'
  name: 'slave02'

# Ports, DON'T CHANGE, these are the deafult ports being used.
rmq_port:
  management_port: '15672'
  server_port: '5672'
  cluster_port1: '4369'
  cluster_port2: '25672'

rabbitmq_erlang_cookie: 'WKRBTTEQRYPTQOPUKSVF'

# Rabbitmq user for cluster login
rabbit_username: 'admin'
rabbit_password: 'password'

# Logging
rabbitmq_logrotate_period: daily
rabbitmq_logrotate_amount: 7
rabbitmq_cluster_log_dir: /var/log/rabbitmq
