
- name: Enable firewalld
  become: yes
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Opening port for rabbitmq management
  become: yes
  command: firewall-cmd --add-port={{ item }}/tcp --permanent
  with_items:
    - "{{ rmq_port.management_port }}"
    - "{{ rmq_port.server_port }}"
    - "{{ rmq_port.cluster_port1 }}"
    - "{{ rmq_port.cluster_port2 }}"

- name: Reload firewalld
  command: firewall-cmd --reload
