- name: Setup hostname for master
  command: hostnamectl --static set-hostname {{ master.name }}
  when: inventory_hostname == "{{ master.name }}"

- name: Setup hostname for master
  command: hostnamectl --static set-hostname {{ slave01.name }}
  when: inventory_hostname == "{{ slave01.name }}"

- name: Setup hostname for master
  command: hostnamectl --static set-hostname {{ slave02.name }}
  when: inventory_hostname == "{{ slave02.name }}"

- name: Setup hosts file of all the cluster nodes (master and slaves)
  blockinfile:
    path: /etc/hosts
    state: present
    insertafter: EOF
    block: |
       {{ master.ip }} {{ master.name }}
       {{ slave01.ip }} {{ slave01.name }}
       {{ slave02.ip }} {{ slave02.name }}

- name: Restart the hostname service
  become: yes
  become_user: root
  become_method: sudo
  command: systemctl restart systemd-hostnamed
